version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.7
      - test-3.8
      - test-3.9
      - test-3.10

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install Python dependencies
      command: CFLAGS="-O0" pip install -r requirements_tests.txt
  - run:
      name: Test
      command: python setup.py test

jobs:
  test-3.7:
    <<: *defaults
    docker:
    - image: cimg/python:3.7
  test-3.8:
    <<: *defaults
    docker:
    - image: cimg/python:3.8
  test-3.9:
    <<: *defaults
    docker:
      - image: cimg/python:3.9
  test-3.10:
    <<: *defaults
    docker:
      - image: cimg/python:3.10
