version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.8

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: sudo pip install -r requirements_tests.txt
  - run:
      name: Test
      command: python setup.py test

jobs:
  test-3.8:
    <<: *defaults
    docker:
    - image: cimg/python:3.8
